"""baseline_mysql

Revision ID: f38390d08da1
Revises: 
Create Date: 2026-02-22 13:37:22.756188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f38390d08da1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inventories', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_index(op.f('ix_inventories_id'), 'inventories', ['id'], unique=False)
    op.alter_column('pos', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('idx_pos_stock_id'), table_name='pos')
    op.create_index(op.f('ix_pos_id'), 'pos', ['id'], unique=False)
    op.alter_column('pos_sessions', 'status',
               existing_type=mysql.ENUM('OPEN', 'CLOSED', collation='utf8mb4_unicode_ci'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('pos_sessions', 'opened_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('pos_sessions', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('idx_pos_sessions_pos_id'), table_name='pos_sessions')
    op.drop_index(op.f('idx_pos_sessions_status'), table_name='pos_sessions')
    op.create_index(op.f('ix_pos_sessions_id'), 'pos_sessions', ['id'], unique=False)
    op.alter_column('products', 'price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('products', 'quantity',
               existing_type=mysql.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('products', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('idx_products_stock_id'), table_name='products')
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.alter_column('stocks', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('idx_stocks_inventory_id'), table_name='stocks')
    op.create_index(op.f('ix_stocks_id'), 'stocks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stocks_id'), table_name='stocks')
    op.create_index(op.f('idx_stocks_inventory_id'), 'stocks', ['inventory_id'], unique=False)
    op.alter_column('stocks', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.create_index(op.f('idx_products_stock_id'), 'products', ['stock_id'], unique=False)
    op.alter_column('products', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('products', 'quantity',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('products', 'price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               server_default=sa.text("'0.00'"),
               existing_nullable=False)
    op.drop_index(op.f('ix_pos_sessions_id'), table_name='pos_sessions')
    op.create_index(op.f('idx_pos_sessions_status'), 'pos_sessions', ['status'], unique=False)
    op.create_index(op.f('idx_pos_sessions_pos_id'), 'pos_sessions', ['pos_id'], unique=False)
    op.alter_column('pos_sessions', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('pos_sessions', 'opened_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('pos_sessions', 'status',
               existing_type=mysql.ENUM('OPEN', 'CLOSED', collation='utf8mb4_unicode_ci'),
               server_default=sa.text("'OPEN'"),
               existing_nullable=False)
    op.drop_index(op.f('ix_pos_id'), table_name='pos')
    op.create_index(op.f('idx_pos_stock_id'), 'pos', ['stock_id'], unique=False)
    op.alter_column('pos', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_index(op.f('ix_inventories_id'), table_name='inventories')
    op.alter_column('inventories', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###
